@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2FvanBtb3JlaXJhMjVAZ21haWwuY29tIiwiaWF0IjoxNzcyNDc2ODcxLCJleHAiOjE3NzUwNjg4NzF9.wY3iz1L65dAWoAyhrr0V-PHiU_7zJdaCvSTOX6d-2y0
### Criar pedido
POST {{baseUrl}}/order/create
Content-Type: application/json

{
  "items": [
    {
      "quantity": 1,
      "fk_product_id": 1,
      "complements": [
        {
          "fk_complement_id": 1,
          "quantity": 1
        },
        {
          "fk_complement_id": 2,
          "quantity": 1
        },
        {
          "fk_complement_id": 4,
          "quantity": 1
        }
      ]
    },
    {
      "quantity": 4,
      "fk_product_id": 1,
      "complements": [
        {
          "fk_complement_id": 1,
          "quantity": 2
        },
        {
          "fk_complement_id": 2,
          "quantity": 1
        },
        {
          "fk_complement_id": 4,
          "quantity": 1
        },
        {
          "fk_complement_id": 7,
          "quantity": 1
        },
        {
          "fk_complement_id": 9,
          "quantity": 1
        },
        {
          "fk_complement_id": 8,
          "quantity": 1
        }
      ]
    },
    {
      "quantity": 2,
      "fk_product_id": 2,
      "complements": [
        {
          "fk_complement_id": 4,
          "quantity": 1
        },
        {
          "fk_complement_id": 7,
          "quantity": 1
        }
      ]
    }
  ],
  "fk_store_id": 2,
  "observation": "",
  "delivery_fee": 5,
  "total_amount": 87.93,
  "delivery_method": "entrega",
  "delivery_address": "Av. Das Palmeiras, 875 - Antártica, Praia Grande - SP ",
  "fk_store_delivery_areas_id": 2,
  "payment_method": "pix",
  "payment_type": "online"
}
### Buscar todos pedido
GET {{baseUrl}}/order/all?fk_store_id=2
Content-Type: application/json
Authorization: Bearer {{token}}
### Buscar pedido por ID
GET {{baseUrl}}/order/42
Content-Type: application/json
### Resolver carrinho
POST {{baseUrl}}/cart/resolve
Content-Type: application/json

{
  "fk_store_id": 2,
  "items": [
    {
      "fk_product_id": 1,
      "quantity": 2,
      "complements": [
        {
          "fk_complement_id": 1,
          "quantity": 1
        }
      ]
    }
  ]
}
### Atualizar um pedido
PUT {{baseUrl}}/order/update
Content-Type: application/json

{
  "id": 2,
  "data": {
    "paid": true,
    "status": "confirmado"
  }
}
### Deletar pedido
DELETE  {{baseUrl}}/order/delete
Content-Type: application/json

{
  "id": 2
}