@baseUrl = http://localhost:3000/api
### Criar sessão
POST {{baseUrl}}/session/create
Content-Type: application/json

{
  "items": [
    {
      "quantity": 2,
      "fk_product_id": 1,
      "complements": [
        {
          "fk_complement_id": 1,
          "quantity": 2
        },
        {
          "fk_complement_id": 2,
          "quantity": 1
        },
        {
          "fk_complement_id": 4,
          "quantity": 1
        },
        {
          "fk_complement_id": 7,
          "quantity": 1
        },
        {
          "fk_complement_id": 8,
          "quantity": 1
        }
      ]
    },
    {
      "quantity": 4,
      "fk_product_id": 2,
      "complements": [
        {
          "fk_complement_id": 1,
          "quantity": 1
        },
        {
          "fk_complement_id": 8,
          "quantity": 1
        }
      ]
    }
  ],
  "fk_store_id": 2,
  "observation": "",
  "delivery_method": "entrega",
  "delivery_address": "Av. Das Palmeiras, 875 - Antártica, Praia Grande - SP "
}
### Buscar sessão por ID
GET {{baseUrl}}/session/checkout:3530fd22-1397-43d5-b80d-2e7197c8fe1b
### Atualizar um sessão
PUT {{baseUrl}}/session/update/checkout:3530fd22-1397-43d5-b80d-2e7197c8fe1b
Content-Type: application/json

{
  "data": {
      "fk_store_delivery_areas_id": 2
  }
}
### Finalizar pedido
POST {{baseUrl}}/session/finish/checkout:3530fd22-1397-43d5-b80d-2e7197c8fe1b