@baseUrl = http://localhost:3000/api
### Criar sessão
POST {{baseUrl}}/session/create
Content-Type: application/json

{
  "items": [
    {
      "quantity": 2,
      "fk_product_id": 1,
      "complements": [
        {
          "fk_complement_id": 1,
          "quantity": 2
        },
        {
          "fk_complement_id": 2,
          "quantity": 1
        },
        {
          "fk_complement_id": 4,
          "quantity": 1
        },
        {
          "fk_complement_id": 7,
          "quantity": 1
        },
        {
          "fk_complement_id": 8,
          "quantity": 1
        }
      ]
    },
    {
      "quantity": 4,
      "fk_product_id": 2,
      "complements": [
        {
          "fk_complement_id": 1,
          "quantity": 1
        },
        {
          "fk_complement_id": 8,
          "quantity": 1
        }
      ]
    }
  ],
  "fk_store_id": 2,
  "observation": "",
  "delivery_method": "entrega",
  "delivery_address": "Av. Das Palmeiras, 875 - Antártica, Praia Grande - SP ",
  "fk_store_delivery_area_id": 2
}
### Buscar sessão por ID
GET {{baseUrl}}/session/checkout:a3b8967c-d022-4607-9e79-205c139b6638
### Atualizar um sessão
PUT {{baseUrl}}/session/update/checkout:a3b8967c-d022-4607-9e79-205c139b6638
Content-Type: application/json

{
  "data": {
    "paid": "true",
    "status": "recebido",
    "mercadopago_pay_id": null,
    "created_at": "2025-07-14 22:23:12",
    "fk_store_delivery_area_id": null,
    "fk_user_id": null,
    "fk_store_id": 1,
  }
}
### Finalizar pedido
POST {{baseUrl}}/session/finish/checkout:a3b8967c-d022-4607-9e79-205c139b6638