@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2FvanBtb3JlaXJhMjVAZ21haWwuY29tLmJyIiwiaWF0IjoxNzcwMTg2MTk3LCJleHAiOjE3NzI3NzgxOTd9.e3cjGtvMRKS8o9DGycYV4ZjZ0d0-Y7Gj6NxUTpW5AK8
### Criar usuário
POST {{baseUrl}}/store/create
Content-Type: application/json

{
  "name": "aNabih Esfiha'ss",
  "email": "babaca@sdasdasd.com",
  "password": "pingu2004"
}
### Cadastrar loja
POST {{baseUrl}}/store/login
Content-Type: application/json

{
  "email": "joaojpmoreira26@gmail.com.br",
  "password": "senha123"
}
### Buscar status da loja
GET {{baseUrl}}/store/status/2
### Buscar loja por ID
GET {{baseUrl}}/store/1
### Buscar loja por slug
GET {{baseUrl}}/store/public/caldinho-da-ashley
Authorization: Bearer {{token}}
### Buscar token
GET {{baseUrl}}/store/status/2
Authorization: Bearer {{token}}
### Verificar status do Mercado Pago
GET {{baseUrl}}/store/check-mercadopago/2
Authorization: Bearer {{token}}
### Atualizar um loja
PUT {{baseUrl}}/store/update/1
Content-Type: application/json

{
  "data": {
    "mercadopago_access_token": "TEST-3453465143454768-450435-034535dbfb0a405344d6ab8bd4ce9e97-1234565339"
  }
}