@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2FvanBtb3JlaXJhMjVAZ21haWwuY29tIiwiaWF0IjoxNzczMDgxOTAyLCJleHAiOjE3NzU2NzM5MDJ9.jES2PQMRA7dOFGduguzpIypO96uKHIkPX4MAUZhYH20
### Criar usuário
POST {{baseUrl}}/store/create
Content-Type: application/json

{
  "name": "aNabih Esfiha'ss",
  "email": "abc@abc.com",
  "password": "senha1234",
  "cpf": "13991027026",
  "phone": "49827089838"
}
### Cadastrar loja
POST {{baseUrl}}/store/login
Content-Type: application/json

{
  "email": "joaojpmoreira26@gmail.com.br",
  "password": "senha123"
}
### Buscar status da loja
GET {{baseUrl}}/store/status/2
### Buscar loja por ID
GET {{baseUrl}}/store/1
### Buscar loja por slug
GET {{baseUrl}}/store/public/caldinho-da-ashley
Authorization: Bearer {{token}}
### Buscar token
GET {{baseUrl}}/store/status/19
Authorization: Bearer {{token}}
### Verificar status do Mercado Pago
GET {{baseUrl}}/store/check-mercadopago/2
Authorization: Bearer {{token}}
### Atualizar um loja
PUT {{baseUrl}}/store/update/1
Content-Type: application/json

{
  "data": {
    "mercadopago_access_token": "TEST-3453465143454768-450435-034535dbfb0a405344d6ab8bd4ce9e97-1234565339"
  }
}